name: conflibot
on: pull_request_target

jobs:
  conflibot:
    runs-on: my-runner
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            yarn.lock
            **/*.bin
